import { addOffer, selectOffer, updateDealDetails, updateDealStage } from '@/actions/deals';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { requireUser } from '@/lib/auth';
import { PIPELINE_STAGES } from '@/lib/utils';
import { createClient } from '@/lib/supabase/server';

export default async function DealDetailPage({ params }: { params: { id: string } }) {
 const { profile } = await requireUser(); const supabase = await createClient(); let q = supabase.from('deals').select('*').eq('id', params.id); if (profile.role === 'rep') q=q.eq('assigned_rep_id', profile.id); const { data: deal } = await q.single(); const { data: offers } = await supabase.from('offers').select('*').eq('deal_id', params.id).order('created_at',{ascending:false}); if (!deal) return <p>Deal not found.</p>;
 const selected = offers?.find((o)=>o.id===deal.selected_offer_id);
 return <div className="space-y-4"><div className="flex items-center justify-between"><h1 className="text-2xl font-semibold">{deal.business_name}</h1><Badge>{deal.current_stage}</Badge></div>
 <Card><h2 className="mb-2 text-lg font-medium">Stage Movement</h2><form action={updateDealStage} className="flex gap-2"><input type="hidden" name="deal_id" value={deal.id}/><select name="current_stage" defaultValue={deal.current_stage} className="rounded-md border px-3 py-2 text-sm">{PIPELINE_STAGES.map((s)=><option key={s}>{s}</option>)}</select><Button type="submit">Move Stage</Button></form></Card>
 <Card><h2 className="mb-2 text-lg font-medium">Operational Checklist</h2><form action={updateDealDetails} className="grid grid-cols-1 gap-2 md:grid-cols-3"><input type="hidden" name="deal_id" value={deal.id}/><input type="hidden" name="selected_offer_payment_frequency" value={selected?.payment_frequency ?? ''}/><input type="hidden" name="selected_offer_term_payments" value={selected?.term_payments ?? ''}/><Input type="date" name="funded_date" defaultValue={deal.funded_date ?? ''}/><Input type="number" step="0.01" name="funded_amount" defaultValue={deal.funded_amount ?? 0}/><Input type="number" step="0.01" name="gross_commission" defaultValue={deal.gross_commission ?? 0}/><label><input type="checkbox" name="application_complete" defaultChecked={deal.application_complete}/> Application complete</label><label><input type="checkbox" name="docs_collected" defaultChecked={deal.docs_collected}/> Statements/docs collected</label><label><input type="checkbox" name="submission_ready" defaultChecked={deal.submission_ready}/> Submission ready</label><label><input type="checkbox" name="dl_received" defaultChecked={deal.dl_received}/> DL received</label><label><input type="checkbox" name="voided_check_received" defaultChecked={deal.voided_check_received}/> Voided check received</label><Input type="date" name="contracts_sent_date" defaultValue={deal.contracts_sent_date ?? ''}/><Input name="kif_reason" defaultValue={deal.kif_reason ?? ''} placeholder="KIF reason" className="md:col-span-3"/><textarea name="underwriting_notes" defaultValue={deal.underwriting_notes ?? ''} className="min-h-20 rounded-md border p-2 text-sm md:col-span-3" placeholder="Underwriting notes"/><textarea name="notes" defaultValue={deal.notes ?? ''} className="min-h-20 rounded-md border p-2 text-sm md:col-span-3"/><Button type="submit" className="md:col-span-3">Save workflow details</Button></form>
 <p className="text-sm text-muted-foreground">Commission payout: {deal.commission_payout_date ?? '—'} · 50% paid / renewal: {deal.renewal_eligibility_date ?? 'Cannot calculate until selected offer term + payment frequency are set.'}</p></Card>
 <Card><h2 className="mb-2 text-lg font-medium">Funder Responses / Offers</h2><form action={addOffer} className="grid grid-cols-1 gap-2 md:grid-cols-4"><input type="hidden" name="deal_id" value={deal.id}/><Input name="funder" placeholder="Funder" required/><select name="decision" className="rounded-md border px-3 py-2 text-sm"><option value="approval">approval</option><option value="decline">decline</option></select><Input name="decline_reason" placeholder="Decline reason"/><Input name="approval_amount" placeholder="Amount"/><Input name="term" placeholder="Term text"/><Input name="term_payments" placeholder="# of payments"/><Input name="payment_frequency" placeholder="daily / weekly / biweekly / monthly"/><Input name="factor_rate" placeholder="factor"/><Input name="payment_amount" placeholder="payment amount"/><Input name="total_payback" placeholder="total payback"/><Input name="stipulations" placeholder="stipulations"/><Button type="submit">Add response</Button></form>
 <div className="mt-4 space-y-2">{offers?.map((o)=><div key={o.id} className="rounded border p-2 text-sm"><p className="font-medium">{o.funder} · {o.decision}</p><p>${Number(o.approval_amount||0).toLocaleString()} · {o.term} · {o.payment_frequency}</p><p>{o.decline_reason || o.stipulations || '—'}</p><form action={selectOffer}><input type="hidden" name="deal_id" value={deal.id}/><input type="hidden" name="offer_id" value={o.id}/><Button type="submit">Select Offer</Button></form></div>)}</div></Card></div>;
}
